name: ${project.name}
version: ${project.version}
api-version: '1.13'
main: me.lokka30.bettercommandspy.BetterCommandSpy
author: lokka30
description: ${project.description}
commands:
  commandspy:
    description: Manage the plugin.
    usage: /<command> [on/off/reload]
    aliases: [bettercommandspy, cspy, cmdspy]
permissions:
  bettercommandspy.toggle:
    default: op
    description: Ability to set commandspy on / off (/commandspy on/off)
  bettercommandspy.toggle.others:
    default: op
    description: Ability to toggle commandspy for other players
    children:
      bettercommandspy.toggle: true
  bettercommandspy.reload:
    default: op
    description: Ability to reload the configuration (/commandspy reload)
  bettercommandspy.bypass:
    default: none
    description: Commands sent from users with this permission will not be shown in command spy.