#  _____    _____   _____
# |  __ \  /  __ \ /  ___\
# | |_/ / | /  \_/ `--.
# |  __ \ | |   __ `--. \
# | |_/ / | \__/ / ,__/ /
# \____/   \____/ \____/

# <!> WARNING - NOT A CONFIG! <!>
# This is not a configuration file!
# This file is used by your server
# software when it loads the plugin.

# About the plugin
name: 'BetterCommandSpy'
version: '${project.version}'
description: '${project.description}'
authors: [ 'lokka30' ]

# Information for Bukkit
main: 'me.lokka30.bettercommandspy.BetterCommandSpy' # Path to the main class
api-version: '1.13' # Leave at '1.13', not the latest version, or it won't start on older versions.

# Commands registered by the plugin
commands:
  bettercommandspy:
    description: 'Manage BetterCommandSpy.'
    usage: '/<command>'
    aliases: [ 'bcs', 'commandspy', 'cspy', 'cmdspy', 'cs' ]

# Permissions this plugin checks
permissions:
  bettercommandspy.*:
    default: 'op'
    description: 'Receive all permissions from the BetterCommandSpy plugin.'
    children:
      bettercommandspy.canListen: true
      bettercommandspy.command.bettercommandspy.toggle: true
      bettercommandspy.command.bettercommandspy.toggle.others: true
      bettercommandspy.command.bettercommandspy.reload: true
      bettercommandspy.command.bettercommandspy.info: true
      bettercommandspy.command.bettercommandspy.compatibility: true
      bettercommandspy.bypass: true

  bettercommandspy.canListen:
    default: 'op'
    description: 'Ability for a player to view command spy alerts.'

  bettercommandspy.command.bettercommandspy.toggle:
    default: 'op'
    description: 'Ability to run the command `/bcs on` and `/bcs off`.'
    children:
      bettercommandspy.canListen: true

  bettercommandspy.command.bettercommandspy.toggle.others:
    default: 'op'
    description: 'Ability to run the command `/bcs on` and `/bcs off` for other players.'
    children:
      bettercommandspy.toggle: true
      bettercommandspy.canListen: true

  bettercommandspy.command.bettercommandspy.reload:
    default: 'op'
    description: 'Ability to run the command `/bcs reload`.'

  bettercommandspy.command.bettercommandspy.info:
    default: true
    description: 'Ability to run the command `/bcs info`.'

  bettercommandspy.command.bettercommandspy.compatibility:
    default: 'op'
    description: 'Ability to run the command `/bcs compatibility`.'

  bettercommandspy.bypass:
    default: false
    description: 'Commands sent from users with this permission will not be shown in command spy.'